### ISSUE TITLE
Update Windows documentation (32 -> 64 bit)

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-user-manual#8]
Update Windows documentation (32 -> 64 bit)

**Comment by PeterBowman** [comment]
@jgvictores can we close this with https://github.com/asrob-uc3m/robotDevastation-user-manual/compare/58a4799...aa35659 or is it not done yet?

**Comment by jgvictores** [comment]
Yes, definitely! 
Was just to keep track of progress. 
Thanks!!
